### ISSUE TITLE
Task List - select current working task Bug

### ISSUE THREAD

**Issue by dnthem** [cse112-sp22-group5/cse112-sp22-group5#20]
How to recreate the bug: 
- Add more than one task to the list.
- Click on the label of a task except for the first task.
- The first task will be chosen -> it should be the task that was clicked on

**Comment by Jazmusic1234** [comment]
Fixed.

Problem:
The 'for' attribute for the labels and the 'id' attributes for the radio input were the same for all the tasks so when you clicked on a label, it selected the first task with the corresponding 'id'.

Solution:
Changed 'for' attribute and 'id' attribute to the corresponding task name.
