### ISSUE TITLE
Refactoring CSS

### ISSUE THREAD

**Issue by Jazmusic1234** [cse112-sp22-group5/cse112-sp22-group5#3]

**Comment by EthanWadsworth** [comment]
- [ ] Reorganize the CSS file into global, section elements, and media queries
- [ ] Reorganize the HTML file to be more semantic (dialogs, removal of Bootstrap, etc)
- [ ] Refactor the HTML to be organized semantically by section and add dialogs for native modal support
- [ ] Remove unused styles and unnecessary root styles
- [ ] Change methods of element positioning (removal of relative and absolute positioning)
