### ISSUE TITLE
Side navbar

### ISSUE THREAD

**Issue by Jazmusic1234** [cse112-sp22-group5/cse112-sp22-group5#31]
- [x] Add navbar (instruction, settings, task list)
- [x] Change CSS to match [UI design](https://xd.adobe.com/view/19ecfd56-28ef-4ac6-bd1a-0cf400170cbd-4cbf/screen/7cf14922-8f69-4a36-b420-c2cc116e8b5b)
- [x] Remove task list from main page
- [x] Add set to default button on settings page

**Comment by dnthem** [comment]
Updates - side navbar > task list
- To select the current task, click on the whole <li> tag to select (the old way is to click on the label)
- To check off a task click on the check box
- edit task - let the user edit it directly to the task when the edit button is clicked (the old way is through a pop-up)
- delete a single task can be performed by its delete button
- More responsive and intuitive

**Comment by dnthem** [comment]
updates - 05/23/2022
- updated and improved UI/UX for small screen devices

**Comment by Jazmusic1234** [comment]
- [ ] change it so the side bar does not collapse between panels
