### ISSUE TITLE
Page overlay on side bar open

### ISSUE THREAD

**Issue by Jazmusic1234** [cse112-sp22-group5/cse112-sp22-group5#67]

**Comment by dnthem** [comment]
Is it the sidebar closes upon resizing the page? This is my intentional choice. The reason behind this is when resizing the webpage, it breaks the panel layout.

**Comment by Jazmusic1234** [comment]
No, this was something that Sanat suggested. Essentially, when the side bar panel opens, it would push the page to the right rather than opening on top of it. But I don't think we are going with that option. I think Ethan is working on creating an overlap which will blur/darken the page so the focus is on the panel when it's open.

**Comment by dnthem** [comment]
Ok, I see. I could do this if time permits
